/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTextBrowser *RealTimeInfo;
    QTextEdit *AddTimeReq;
    QTextBrowser *AddPlan;
    QLabel *label_9;
    QLabel *label;
    QPushButton *Stop;
    QPushButton *Search;
    QLabel *label_6;
    QLabel *label_18;
    QTextBrowser *SeqAllocate;
    QTextEdit *AddDepart;
    QPushButton *AddPas;
    QLabel *label_22;
    QLabel *label_23;
    QTextEdit *SearchSeq;
    QTextEdit *AddDest;
    QPushButton *Pause;
    QLabel *label_3;
    QLabel *label_5;
    QPushButton *Start;
    QLabel *label_8;
    QLabel *label_2;
    QTextEdit *AddPriceReq;
    QTextEdit *AddRiskReq;
    QTextEdit *SearchTime;
    QLabel *label_10;
    QLabel *label_7;
    QLabel *label_20;
    QTextBrowser *PasState;
    QLabel *label_4;
    QLCDNumber *TIME;
    QLabel *label_24;
    QLabel *LBL_PIC;
    QLabel *fuzhou;
    QLabel *guangzhou;
    QLabel *changsha;
    QLabel *chengdu;
    QLabel *kunming;
    QLabel *wuhan;
    QLabel *nanjing;
    QLabel *beijing;
    QLabel *shenyang;
    QLabel *lanzhou;
    QLabel *haerbin;
    QLabel *xian;
    QLabel *hashen;
    QLabel *shenbei;
    QLabel *beinan;
    QLabel *beiwu;
    QLabel *beixi;
    QLabel *lanxi;
    QLabel *shenlan;
    QLabel *xiwu;
    QLabel *nanwu;
    QLabel *xicheng;
    QLabel *xikun;
    QLabel *chengchang;
    QLabel *chengkun;
    QLabel *wuchang;
    QLabel *wufu;
    QLabel *changkun;
    QLabel *changguang;
    QLabel *fuguang;
    QLabel *chengfu;
    QLabel *nanguang;
    QLabel *label_21;
    QRadioButton *Radio_Time;
    QRadioButton *Radio_Risk;
    QRadioButton *Radio_Price;
    QRadioButton *Radio_None;
    QLabel *label_11;
    QRadioButton *Radio_UpdateSpeed_1;
    QRadioButton *Radio_UpdateSpeed_5;
    QLabel *label_12;
    QRadioButton *Radio_UpdateSpeed_10;
    QMenuBar *menuBar;
    QMenu *menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(791, 578);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        RealTimeInfo = new QTextBrowser(centralWidget);
        RealTimeInfo->setObjectName(QStringLiteral("RealTimeInfo"));
        RealTimeInfo->setGeometry(QRect(490, 40, 281, 131));
        QFont font;
        font.setPointSize(9);
        RealTimeInfo->setFont(font);
        AddTimeReq = new QTextEdit(centralWidget);
        AddTimeReq->setObjectName(QStringLiteral("AddTimeReq"));
        AddTimeReq->setGeometry(QRect(700, 280, 71, 21));
        AddTimeReq->setFont(font);
        AddPlan = new QTextBrowser(centralWidget);
        AddPlan->setObjectName(QStringLiteral("AddPlan"));
        AddPlan->setGeometry(QRect(490, 480, 281, 41));
        AddPlan->setFont(font);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(490, 400, 201, 16));
        QFont font1;
        font1.setPointSize(12);
        label_9->setFont(font1);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(490, 10, 161, 21));
        QFont font2;
        font2.setPointSize(18);
        label->setFont(font2);
        Stop = new QPushButton(centralWidget);
        Stop->setObjectName(QStringLiteral("Stop"));
        Stop->setGeometry(QRect(10, 490, 71, 31));
        QFont font3;
        font3.setPointSize(15);
        Stop->setFont(font3);
        Search = new QPushButton(centralWidget);
        Search->setObjectName(QStringLiteral("Search"));
        Search->setGeometry(QRect(310, 500, 41, 21));
        Search->setFont(font1);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(490, 220, 141, 16));
        label_6->setFont(font1);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(490, 310, 201, 16));
        label_18->setFont(font1);
        SeqAllocate = new QTextBrowser(centralWidget);
        SeqAllocate->setObjectName(QStringLiteral("SeqAllocate"));
        SeqAllocate->setGeometry(QRect(700, 430, 71, 21));
        SeqAllocate->setFont(font);
        AddDepart = new QTextEdit(centralWidget);
        AddDepart->setObjectName(QStringLiteral("AddDepart"));
        AddDepart->setGeometry(QRect(700, 220, 71, 21));
        AddDepart->setFont(font);
        AddPas = new QPushButton(centralWidget);
        AddPas->setObjectName(QStringLiteral("AddPas"));
        AddPas->setGeometry(QRect(700, 400, 71, 20));
        AddPas->setFont(font1);
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(180, 470, 121, 21));
        label_22->setFont(font1);
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(180, 500, 121, 16));
        label_23->setFont(font1);
        SearchSeq = new QTextEdit(centralWidget);
        SearchSeq->setObjectName(QStringLiteral("SearchSeq"));
        SearchSeq->setGeometry(QRect(310, 440, 41, 21));
        SearchSeq->setFont(font);
        AddDest = new QTextEdit(centralWidget);
        AddDest->setObjectName(QStringLiteral("AddDest"));
        AddDest->setGeometry(QRect(700, 250, 71, 21));
        AddDest->setFont(font);
        Pause = new QPushButton(centralWidget);
        Pause->setObjectName(QStringLiteral("Pause"));
        Pause->setGeometry(QRect(90, 490, 71, 31));
        Pause->setFont(font3);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(180, 440, 121, 21));
        label_3->setFont(font1);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(490, 430, 161, 16));
        label_5->setFont(font1);
        Start = new QPushButton(centralWidget);
        Start->setObjectName(QStringLiteral("Start"));
        Start->setGeometry(QRect(10, 450, 151, 31));
        Start->setFont(font3);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(490, 280, 191, 16));
        label_8->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(210, 400, 271, 31));
        label_2->setFont(font2);
        AddPriceReq = new QTextEdit(centralWidget);
        AddPriceReq->setObjectName(QStringLiteral("AddPriceReq"));
        AddPriceReq->setGeometry(QRect(700, 340, 71, 21));
        AddPriceReq->setFont(font);
        AddRiskReq = new QTextEdit(centralWidget);
        AddRiskReq->setObjectName(QStringLiteral("AddRiskReq"));
        AddRiskReq->setGeometry(QRect(700, 310, 71, 21));
        AddRiskReq->setFont(font);
        SearchTime = new QTextEdit(centralWidget);
        SearchTime->setObjectName(QStringLiteral("SearchTime"));
        SearchTime->setGeometry(QRect(310, 470, 41, 21));
        SearchTime->setFont(font);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(490, 460, 101, 16));
        label_10->setFont(font1);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(490, 250, 141, 16));
        label_7->setFont(font1);
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(490, 340, 201, 16));
        label_20->setFont(font1);
        PasState = new QTextBrowser(centralWidget);
        PasState->setObjectName(QStringLiteral("PasState"));
        PasState->setGeometry(QRect(360, 440, 121, 81));
        PasState->setFont(font);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(500, 190, 171, 21));
        label_4->setFont(font2);
        TIME = new QLCDNumber(centralWidget);
        TIME->setObjectName(QStringLiteral("TIME"));
        TIME->setGeometry(QRect(80, 20, 61, 23));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(30, 20, 51, 21));
        label_24->setFont(font2);
        LBL_PIC = new QLabel(centralWidget);
        LBL_PIC->setObjectName(QStringLiteral("LBL_PIC"));
        LBL_PIC->setGeometry(QRect(10, 10, 471, 381));
        LBL_PIC->setAutoFillBackground(false);
        LBL_PIC->setStyleSheet(QLatin1String("\n"
"border-image: url(:/new/mapc.jpg);"));
        LBL_PIC->setScaledContents(false);
        fuzhou = new QLabel(centralWidget);
        fuzhou->setObjectName(QStringLiteral("fuzhou"));
        fuzhou->setGeometry(QRect(300, 320, 31, 31));
        guangzhou = new QLabel(centralWidget);
        guangzhou->setObjectName(QStringLiteral("guangzhou"));
        guangzhou->setGeometry(QRect(220, 350, 31, 31));
        changsha = new QLabel(centralWidget);
        changsha->setObjectName(QStringLiteral("changsha"));
        changsha->setGeometry(QRect(220, 290, 31, 31));
        chengdu = new QLabel(centralWidget);
        chengdu->setObjectName(QStringLiteral("chengdu"));
        chengdu->setGeometry(QRect(100, 260, 31, 31));
        kunming = new QLabel(centralWidget);
        kunming->setObjectName(QStringLiteral("kunming"));
        kunming->setGeometry(QRect(90, 330, 31, 31));
        wuhan = new QLabel(centralWidget);
        wuhan->setObjectName(QStringLiteral("wuhan"));
        wuhan->setGeometry(QRect(240, 250, 31, 31));
        nanjing = new QLabel(centralWidget);
        nanjing->setObjectName(QStringLiteral("nanjing"));
        nanjing->setGeometry(QRect(290, 230, 31, 31));
        beijing = new QLabel(centralWidget);
        beijing->setObjectName(QStringLiteral("beijing"));
        beijing->setGeometry(QRect(250, 120, 31, 31));
        shenyang = new QLabel(centralWidget);
        shenyang->setObjectName(QStringLiteral("shenyang"));
        shenyang->setGeometry(QRect(360, 100, 31, 31));
        lanzhou = new QLabel(centralWidget);
        lanzhou->setObjectName(QStringLiteral("lanzhou"));
        lanzhou->setGeometry(QRect(90, 180, 31, 31));
        haerbin = new QLabel(centralWidget);
        haerbin->setObjectName(QStringLiteral("haerbin"));
        haerbin->setGeometry(QRect(400, 30, 31, 31));
        xian = new QLabel(centralWidget);
        xian->setObjectName(QStringLiteral("xian"));
        xian->setGeometry(QRect(160, 210, 31, 31));
        hashen = new QLabel(centralWidget);
        hashen->setObjectName(QStringLiteral("hashen"));
        hashen->setGeometry(QRect(360, 30, 41, 71));
        hashen->setAlignment(Qt::AlignCenter);
        shenbei = new QLabel(centralWidget);
        shenbei->setObjectName(QStringLiteral("shenbei"));
        shenbei->setGeometry(QRect(270, 100, 91, 21));
        shenbei->setAlignment(Qt::AlignCenter);
        beinan = new QLabel(centralWidget);
        beinan->setObjectName(QStringLiteral("beinan"));
        beinan->setGeometry(QRect(270, 130, 31, 111));
        beinan->setAlignment(Qt::AlignCenter);
        beiwu = new QLabel(centralWidget);
        beiwu->setObjectName(QStringLiteral("beiwu"));
        beiwu->setGeometry(QRect(240, 130, 31, 131));
        beiwu->setAlignment(Qt::AlignCenter);
        beixi = new QLabel(centralWidget);
        beixi->setObjectName(QStringLiteral("beixi"));
        beixi->setGeometry(QRect(170, 130, 91, 81));
        beixi->setAlignment(Qt::AlignCenter);
        lanxi = new QLabel(centralWidget);
        lanxi->setObjectName(QStringLiteral("lanxi"));
        lanxi->setGeometry(QRect(100, 180, 71, 31));
        lanxi->setAlignment(Qt::AlignCenter);
        shenlan = new QLabel(centralWidget);
        shenlan->setObjectName(QStringLiteral("shenlan"));
        shenlan->setGeometry(QRect(100, 100, 261, 81));
        shenlan->setAutoFillBackground(false);
        shenlan->setScaledContents(false);
        shenlan->setAlignment(Qt::AlignCenter);
        xiwu = new QLabel(centralWidget);
        xiwu->setObjectName(QStringLiteral("xiwu"));
        xiwu->setGeometry(QRect(170, 210, 71, 51));
        xiwu->setAlignment(Qt::AlignCenter);
        nanwu = new QLabel(centralWidget);
        nanwu->setObjectName(QStringLiteral("nanwu"));
        nanwu->setGeometry(QRect(240, 239, 61, 20));
        nanwu->setAlignment(Qt::AlignCenter);
        xicheng = new QLabel(centralWidget);
        xicheng->setObjectName(QStringLiteral("xicheng"));
        xicheng->setGeometry(QRect(100, 210, 71, 51));
        xicheng->setAlignment(Qt::AlignCenter);
        xikun = new QLabel(centralWidget);
        xikun->setObjectName(QStringLiteral("xikun"));
        xikun->setGeometry(QRect(90, 210, 81, 121));
        xikun->setAlignment(Qt::AlignCenter);
        chengchang = new QLabel(centralWidget);
        chengchang->setObjectName(QStringLiteral("chengchang"));
        chengchang->setGeometry(QRect(100, 260, 121, 31));
        chengchang->setAlignment(Qt::AlignCenter);
        chengkun = new QLabel(centralWidget);
        chengkun->setObjectName(QStringLiteral("chengkun"));
        chengkun->setGeometry(QRect(80, 260, 41, 81));
        chengkun->setAlignment(Qt::AlignCenter);
        wuchang = new QLabel(centralWidget);
        wuchang->setObjectName(QStringLiteral("wuchang"));
        wuchang->setGeometry(QRect(221, 260, 41, 31));
        wuchang->setAlignment(Qt::AlignCenter);
        wufu = new QLabel(centralWidget);
        wufu->setObjectName(QStringLiteral("wufu"));
        wufu->setGeometry(QRect(240, 260, 71, 61));
        wufu->setAlignment(Qt::AlignCenter);
        changkun = new QLabel(centralWidget);
        changkun->setObjectName(QStringLiteral("changkun"));
        changkun->setGeometry(QRect(90, 288, 131, 51));
        changkun->setAlignment(Qt::AlignCenter);
        changguang = new QLabel(centralWidget);
        changguang->setObjectName(QStringLiteral("changguang"));
        changguang->setGeometry(QRect(220, 290, 41, 71));
        fuguang = new QLabel(centralWidget);
        fuguang->setObjectName(QStringLiteral("fuguang"));
        fuguang->setGeometry(QRect(220, 320, 81, 41));
        fuguang->setAlignment(Qt::AlignCenter);
        chengfu = new QLabel(centralWidget);
        chengfu->setObjectName(QStringLiteral("chengfu"));
        chengfu->setGeometry(QRect(100, 260, 201, 61));
        chengfu->setAlignment(Qt::AlignCenter);
        nanguang = new QLabel(centralWidget);
        nanguang->setObjectName(QStringLiteral("nanguang"));
        nanguang->setGeometry(QRect(230, 240, 71, 121));
        nanguang->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(490, 370, 141, 16));
        label_21->setFont(font1);
        Radio_Time = new QRadioButton(centralWidget);
        Radio_Time->setObjectName(QStringLiteral("Radio_Time"));
        Radio_Time->setGeometry(QRect(670, 370, 31, 16));
        Radio_Time->setFont(font);
        Radio_Risk = new QRadioButton(centralWidget);
        Radio_Risk->setObjectName(QStringLiteral("Radio_Risk"));
        Radio_Risk->setGeometry(QRect(710, 370, 31, 16));
        Radio_Risk->setFont(font);
        Radio_Price = new QRadioButton(centralWidget);
        Radio_Price->setObjectName(QStringLiteral("Radio_Price"));
        Radio_Price->setGeometry(QRect(750, 370, 41, 16));
        Radio_Price->setFont(font);
        Radio_None = new QRadioButton(centralWidget);
        Radio_None->setObjectName(QStringLiteral("Radio_None"));
        Radio_None->setGeometry(QRect(640, 370, 31, 16));
        Radio_None->setFont(font);
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 400, 181, 21));
        label_11->setFont(font1);
        Radio_UpdateSpeed_1 = new QRadioButton(centralWidget);
        Radio_UpdateSpeed_1->setObjectName(QStringLiteral("Radio_UpdateSpeed_1"));
        Radio_UpdateSpeed_1->setGeometry(QRect(70, 420, 31, 16));
        Radio_UpdateSpeed_1->setFont(font);
        Radio_UpdateSpeed_5 = new QRadioButton(centralWidget);
        Radio_UpdateSpeed_5->setObjectName(QStringLiteral("Radio_UpdateSpeed_5"));
        Radio_UpdateSpeed_5->setGeometry(QRect(100, 420, 31, 16));
        Radio_UpdateSpeed_5->setFont(font);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 420, 51, 21));
        label_12->setFont(font);
        Radio_UpdateSpeed_10 = new QRadioButton(centralWidget);
        Radio_UpdateSpeed_10->setObjectName(QStringLiteral("Radio_UpdateSpeed_10"));
        Radio_UpdateSpeed_10->setGeometry(QRect(130, 420, 31, 16));
        Radio_UpdateSpeed_10->setFont(font);
        MainWindow->setCentralWidget(centralWidget);
        LBL_PIC->raise();
        RealTimeInfo->raise();
        AddTimeReq->raise();
        AddPlan->raise();
        label_9->raise();
        label->raise();
        Stop->raise();
        Search->raise();
        label_6->raise();
        label_18->raise();
        SeqAllocate->raise();
        AddDepart->raise();
        AddPas->raise();
        label_22->raise();
        label_23->raise();
        SearchSeq->raise();
        AddDest->raise();
        Pause->raise();
        label_3->raise();
        label_5->raise();
        Start->raise();
        label_8->raise();
        label_2->raise();
        AddPriceReq->raise();
        AddRiskReq->raise();
        SearchTime->raise();
        label_10->raise();
        label_7->raise();
        label_20->raise();
        PasState->raise();
        label_4->raise();
        TIME->raise();
        label_24->raise();
        fuzhou->raise();
        guangzhou->raise();
        changsha->raise();
        chengdu->raise();
        kunming->raise();
        wuhan->raise();
        nanjing->raise();
        beijing->raise();
        shenyang->raise();
        lanzhou->raise();
        haerbin->raise();
        xian->raise();
        hashen->raise();
        shenbei->raise();
        beinan->raise();
        beiwu->raise();
        beixi->raise();
        lanxi->raise();
        shenlan->raise();
        xiwu->raise();
        nanwu->raise();
        xicheng->raise();
        xikun->raise();
        chengchang->raise();
        chengkun->raise();
        wuchang->raise();
        wufu->raise();
        changkun->raise();
        changguang->raise();
        fuguang->raise();
        chengfu->raise();
        nanguang->raise();
        label_21->raise();
        Radio_Time->raise();
        Radio_Risk->raise();
        Radio_Price->raise();
        Radio_None->raise();
        label_11->raise();
        Radio_UpdateSpeed_1->raise();
        Radio_UpdateSpeed_5->raise();
        label_12->raise();
        Radio_UpdateSpeed_10->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 791, 17));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menu->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "\350\276\223\345\205\245\345\256\214\344\273\245\344\270\212\344\277\241\346\201\257\350\257\267\347\202\271\345\207\273\357\274\232", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "\345\256\236\346\227\266\346\266\210\346\201\257\357\274\232", Q_NULLPTR));
        Stop->setText(QApplication::translate("MainWindow", "\347\273\223\346\235\237", Q_NULLPTR));
        Search->setText(QApplication::translate("MainWindow", "\346\237\245\350\257\242", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\345\207\272\345\217\221\345\234\260\357\274\232", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "\351\243\216\351\231\251\350\246\201\346\261\202(\344\270\215\350\276\223\345\205\245\345\210\231\346\227\240\350\246\201\346\261\202):", Q_NULLPTR));
        AddPas->setText(QApplication::translate("MainWindow", "\346\267\273\345\212\240", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\346\237\245\350\257\242\346\227\266\345\210\273\357\274\232", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "\350\276\223\345\205\245\345\256\214\346\257\225\350\257\267\347\202\271\345\207\273\357\274\232", Q_NULLPTR));
        Pause->setText(QApplication::translate("MainWindow", "\346\232\202\345\201\234", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\346\227\205\345\256\242\347\274\226\345\217\267\357\274\232", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "\346\227\205\345\256\242\347\274\226\345\217\267(\350\207\252\345\212\250\345\210\206\351\205\215):", Q_NULLPTR));
        Start->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213/\347\273\247\347\273\255", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "\346\227\266\351\227\264\350\246\201\346\261\202(\344\270\215\350\276\223\345\205\245\345\210\231\346\227\240\350\246\201\346\261\202):", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "\346\227\205\345\256\242\347\212\266\346\200\201\344\277\241\346\201\257\346\237\245\350\257\242", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "\347\255\226\347\225\245\346\226\271\346\241\210\357\274\232", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\347\233\256\347\232\204\345\234\260\357\274\232", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "\347\245\250\344\273\267\350\246\201\346\261\202(\344\270\215\350\276\223\345\205\245\345\210\231\346\227\240\350\246\201\346\261\202):", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "\346\226\260\345\242\236\346\227\205\345\256\242", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "TIME:", Q_NULLPTR));
        LBL_PIC->setText(QApplication::translate("MainWindow", "GRAPH", Q_NULLPTR));
        fuzhou->setText(QString());
        guangzhou->setText(QString());
        changsha->setText(QString());
        chengdu->setText(QString());
        kunming->setText(QString());
        wuhan->setText(QString());
        nanjing->setText(QString());
        beijing->setText(QString());
        shenyang->setText(QString());
        lanzhou->setText(QString());
        haerbin->setText(QString());
        xian->setText(QString());
        hashen->setText(QApplication::translate("MainWindow", "hashen", Q_NULLPTR));
        shenbei->setText(QApplication::translate("MainWindow", "shenbei", Q_NULLPTR));
        beinan->setText(QApplication::translate("MainWindow", "beinan", Q_NULLPTR));
        beiwu->setText(QApplication::translate("MainWindow", "beiwu", Q_NULLPTR));
        beixi->setText(QApplication::translate("MainWindow", "beixi", Q_NULLPTR));
        lanxi->setText(QApplication::translate("MainWindow", "lanxi", Q_NULLPTR));
        shenlan->setText(QApplication::translate("MainWindow", "shenlan", Q_NULLPTR));
        xiwu->setText(QApplication::translate("MainWindow", "xiwu", Q_NULLPTR));
        nanwu->setText(QApplication::translate("MainWindow", "nanwu", Q_NULLPTR));
        xicheng->setText(QApplication::translate("MainWindow", "xicheng", Q_NULLPTR));
        xikun->setText(QApplication::translate("MainWindow", "xikun", Q_NULLPTR));
        chengchang->setText(QApplication::translate("MainWindow", "chengchang", Q_NULLPTR));
        chengkun->setText(QApplication::translate("MainWindow", "chengkun", Q_NULLPTR));
        wuchang->setText(QApplication::translate("MainWindow", "wuchang", Q_NULLPTR));
        wufu->setText(QApplication::translate("MainWindow", "wufu", Q_NULLPTR));
        changkun->setText(QApplication::translate("MainWindow", "changkun", Q_NULLPTR));
        changguang->setText(QApplication::translate("MainWindow", "changguang", Q_NULLPTR));
        fuguang->setText(QApplication::translate("MainWindow", "fuguang", Q_NULLPTR));
        chengfu->setText(QApplication::translate("MainWindow", "chengfu", Q_NULLPTR));
        nanguang->setText(QApplication::translate("MainWindow", "nanguang", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "\344\274\230\345\205\210\350\246\201\346\261\202\357\274\2104\351\200\2111\357\274\214\351\273\230\350\256\244\346\227\240\357\274\211", Q_NULLPTR));
        Radio_Time->setText(QApplication::translate("MainWindow", "\346\227\266\351\227\264", Q_NULLPTR));
        Radio_Risk->setText(QApplication::translate("MainWindow", "\351\243\216\351\231\251", Q_NULLPTR));
        Radio_Price->setText(QApplication::translate("MainWindow", "\347\245\250\344\273\267", Q_NULLPTR));
        Radio_None->setText(QApplication::translate("MainWindow", "\346\227\240", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "\350\256\276\347\275\256\347\263\273\347\273\237\346\227\266\351\227\264\346\233\264\346\226\260\351\200\237\345\272\246\357\274\210\347\247\222/\345\260\217\346\227\266\357\274\211", Q_NULLPTR));
        Radio_UpdateSpeed_1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        Radio_UpdateSpeed_5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "(\351\273\230\350\256\244\344\270\2721)", Q_NULLPTR));
        Radio_UpdateSpeed_10->setText(QApplication::translate("MainWindow", "10", Q_NULLPTR));
        menu->setTitle(QApplication::translate("MainWindow", "\346\227\205\350\241\214\347\263\273\347\273\237", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
